### ISSUE TITLE
node-oracledb 1.9-dev has native promise support

### ISSUE THREAD

**Issue by cjbj** [jsumners/honest-oracledb#1]
Check out the native promise support in the development branch of node-oracledb: https://github.com/oracle/node-oracledb/tree/dev-1.9 

Comments on the design and implementation are welcome at https://github.com/oracle/node-oracledb/issues/410

**Comment by jsumners** [comment]
I see you have a generic "promisify" function in utils.js, but I do not see how it gets applied to all of the oracledb classes and methods. Regardless, I'd love to not have to maintain this library. So I welcome a native implementation.

**Comment by cjbj** [comment]
@jsumners it gets applied by individual calls like these https://github.com/oracle/node-oracledb/blob/dev-1.9/lib/connection.js#L209 when the underlying C++ implementation is extended.

**Comment by jsumners** [comment]
I see. So if you're promisifying every method, why not just write the methods to return promises instead of callbacks?

**Comment by cjbj** [comment]
@jsumners If methods returned only promises would limit programming style and also break backward compatibility.  Can you jump onto the oracledb [issue](https://github.com/oracle/node-oracledb/issues/410) if you have more questions?
